name: Lint

on: workflow_call

permissions:
  contents: write

jobs:
  prettier:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: node:18.15.0-alpine
    steps:
      - name: Install git
        run: apk add git
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run prettier check
        id: prettier_check
        continue-on-error: true
        run: |
          trap 'echo "PRETTIER_EXIT_CODE=$?" >> $GITHUB_OUTPUT' EXIT; npm run prettify:check
      - name: Fail if there no auto fix
        if: steps.prettier_check.outputs.PRETTIER_EXIT_CODE == 2
        run: exit 2
      - name: Run prettier
        id: prettier_run
        if: steps.prettier_check.outputs.PRETTIER_EXIT_CODE == 1
        run: |
          json='{"status": "1"}' && echo "$json" > status.json
      - uses: actions/upload-artifact@v4
        with:
          name: status
          path: 'status.json'
